import type { TargetField } from './types'

export const DATABASE_SCHEMA = {
  tables: {
    time_logs: {
      description: 'Time tracking records for employee work hours',
      fields: {
        id: {
          type: 'UUID',
          description: 'Primary key',
          required: false,
          autoGenerated: true
        },
        user_id: {
          type: 'UUID',
          description: 'Foreign key to profiles table',
          required: true,
          references: 'profiles.id'
        },
        date: {
          type: 'DATE',
          description: 'Work date in YYYY-MM-DD format',
          required: true,
          format: 'YYYY-MM-DD'
        },
        clock_in: {
          type: 'TIMESTAMPTZ',
          description: 'Clock in timestamp in ISO 8601 format',
          required: true,
          format: 'ISO 8601 (YYYY-MM-DDTHH:MM:SSZ)'
        },
        clock_out: {
          type: 'TIMESTAMPTZ',
          description: 'Clock out timestamp in ISO 8601 format',
          required: true,
          format: 'ISO 8601 (YYYY-MM-DDTHH:MM:SSZ)'
        },
        total_hours: {
          type: 'DECIMAL(5,2)',
          description: 'Total hours worked (clock_out - clock_in)',
          required: true,
          constraints: 'total_hours >= 0'
        },
        record_type: {
          type: 'TEXT',
          description: 'Type of record',
          required: true,
          values: ['official', 'personal']
        },
        notes: {
          type: 'TEXT',
          description: 'Optional notes about the record',
          required: false
        },
        is_manual: {
          type: 'BOOLEAN',
          description: 'Whether the record was manually entered',
          required: false,
          default: false
        },
        is_official: {
          type: 'BOOLEAN',
          description: 'Whether this is an official record marked by admin',
          required: false,
          default: false
        }
      },
      constraints: {
        valid_clock_out: 'clock_out > clock_in',
        valid_total_hours: 'total_hours >= 0'
      }
    },
    profiles: {
      description: 'User profiles for employees and admins',
      fields: {
        id: {
          type: 'UUID',
          description: 'Primary key, matches auth.users.id',
          required: true,
          autoGenerated: true
        },
        email: {
          type: 'TEXT',
          description: 'Unique email address',
          required: true,
          format: 'email',
          unique: true
        },
        full_name: {
          type: 'TEXT',
          description: 'Employee full name',
          required: true
        },
        role: {
          type: 'TEXT',
          description: 'User role',
          required: true,
          values: ['employee', 'admin']
        },
        is_active: {
          type: 'BOOLEAN',
          description: 'Whether the account is active',
          required: false,
          default: true
        },
        invitation_status: {
          type: 'TEXT',
          description: 'Invitation tracking status',
          required: false,
          values: ['pending', 'sent', 'accepted', 'expired']
        }
      }
    }
  }
} as const

export const REQUIRED_FIELDS: TargetField[] = ['email', 'date', 'clock_in', 'clock_out']

export const OPTIONAL_FIELDS: TargetField[] = ['full_name', 'notes']

export const DATE_FORMATS_TO_DETECT = [
  { format: 'DD/MM/YYYY', pattern: /^(\d{1,2})\/(\d{1,2})\/(\d{4})$/, example: '16/03/2026' },
  { format: 'MM/DD/YYYY', pattern: /^(\d{1,2})\/(\d{1,2})\/(\d{4})$/, example: '03/16/2026', note: 'US format - detect by context' },
  { format: 'YYYY-MM-DD', pattern: /^(\d{4})-(\d{2})-(\d{2})$/, example: '2026-03-16' },
  { format: 'DD-MM-YYYY', pattern: /^(\d{1,2})-(\d{1,2})-(\d{4})$/, example: '16-03-2026' },
  { format: 'DD.MM.YYYY', pattern: /^(\d{1,2})\.(\d{1,2})\.(\d{4})$/, example: '16.03.2026' },
  { format: 'DD_MM_YYYY', pattern: /^(\d{1,2})_(\d{1,2})_(\d{4})$/, example: '16_03_2026' },
  { format: 'YYYY/MM/DD', pattern: /^(\d{4})\/(\d{1,2})\/(\d{1,2})$/, example: '2026/03/16' }
] as const

export const TIME_FORMATS_TO_DETECT = [
  { format: 'HH:MM', pattern: /^(\d{1,2}):(\d{2})$/, example: '08:55', normalize: (h: number, m: number) => `${h.toString().padStart(2, '0')}:${m.toString().padStart(2, '0')}` },
  { format: 'HH:MM:SS', pattern: /^(\d{1,2}):(\d{2}):(\d{2})$/, example: '08:55:30' },
  { format: 'H:MM', pattern: /^(\d{1,2}):(\d{2})$/, example: '8:55', normalize: (h: number, m: number) => `${h.toString().padStart(2, '0')}:${m.toString().padStart(2, '0')}` },
  { format: 'H:MM:SS', pattern: /^(\d{1,2}):(\d{2}):(\d{2})$/, example: '8:55:30' },
  { format: '12h_AM_PM', pattern: /^(\d{1,2}):(\d{2})\s*(AM|PM|am|pm)$/, example: '8:55 AM', normalize: (h: number, m: number, ampm: string) => { const hour = ampm.toUpperCase() === 'PM' && h !== 12 ? h + 12 : (ampm.toUpperCase() === 'AM' && h === 12 ? 0 : h); return `${hour.toString().padStart(2, '0')}:${m.toString().padStart(2, '0')}` } },
  { format: 'decimal_excel', description: 'Excel decimal format where 0.354167 represents 8:30 AM', example: '0.354167' }
] as const

export const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/

export function getSchemaForPrompt(): string {
  const schema = DATABASE_SCHEMA
  
  let prompt = `## Database Schema\n\n`
  prompt += `### time_logs table\n`
  prompt += `Primary fields:\n`
  prompt += `- date: DATE in YYYY-MM-DD format\n`
  prompt += `- clock_in: TIMESTAMPTZ in ISO 8601 format (e.g., "2026-03-16T08:55:00Z")\n`
  prompt += `- clock_out: TIMESTAMPTZ in ISO 8601 format\n`
  prompt += `- total_hours: DECIMAL, calculated as clock_out - clock_in\n`
  prompt += `- record_type: 'official' or 'personal'\n\n`
  prompt += `### profiles table\n`
  prompt += `- email: TEXT, unique identifier for employees\n`
  prompt += `- full_name: TEXT, employee full name\n\n`
  prompt += `## Important Constraints\n`
  prompt += `- clock_out must be AFTER clock_in\n`
  prompt += `- total_hours must be >= 0\n`
  prompt += `- date must be valid and not in the future\n`
  
  return prompt
}
